name: Audit Modules

on:
  push:
    branches:
      # - testing
      - 181-automation-create-github-action-to-verify-module-format
  pull_request:
    branches:
      - testing
      - ready
      - deployed

jobs:
  check-files:
    runs-on: ubuntu-latest
    name: Check Files

    steps:

      - name: Checkout Repository
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Check Files
        id: check-files
        run: |
          echo "job: running script to check changed files:"
          chmod +x ./.github/workflows/audit.sh
          ./.github/workflows/audit.sh
          echo "job: Done"
        # outputs:
        #   manifest-check-output:
        #     description: Checks for manifest.yml

#       - name: Manifest Check Pass
#         if: steps.check-files.outputs.manifest-check-output == "pass"
#         run: exit 1
