name: Audit Modules

on:
  push:

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Check Files
      id: check-files
      run: |
        echo "job: running script to check changed files:"
        chmod +x ./.github/workflows/audit.sh
        ./.github/workflows/audit.sh
        echo "job: Done"

    - name: Manifest Check Pass
      if: steps.check-files.outputs.manifest-check-output == pass
      run: exit 1
